export type LyricSection = { label: string; lines: string[] };
export type Lyrics = { title: string | null; sections: LyricSection[] };

export type Song = {
  id: string;
  title: string;
  key: string | null;
  ccli: string | null;
  artist: string | null;
  tempo: string | null;
  time: string | null;
  choRaw: string | null;
  lyrics: Lyrics | null;
  // AI-merged chart: chart chords positioned over the TCC lyric wording.
  // Generated by `npm run merge` into songs/merged/<id>.cho (committed); null if absent.
  merged: string | null;
  sourceFiles: { cho: string | null; docx: string | null };
};

export type SongsData = { songs: Song[]; builtAt: string };
